---
development:
  cloud_name: dxe9w9yyw
  api_key: '918685653793144'
  api_secret: ujLZGL03Klv9K60styKHzrtFEMY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dxe9w9yyw
  api_key: '918685653793144'
  api_secret: ujLZGL03Klv9K60styKHzrtFEMY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dxe9w9yyw
  api_key: '918685653793144'
  api_secret: ujLZGL03Klv9K60styKHzrtFEMY
  enhance_image_tag: true
  static_file_support: false
